server:
  port: 8080
  servlet:
    context-path: /api    # 接口统一前缀 /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: Whu123456   # 生产环境建议用环境变量替换
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:              # 连接池优化配置（可选）
      connection-timeout: 30000
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jpa:
    hibernate:
      ddl-auto: update   # 开发用update，生产建议改为validate
    show-sql: true       # 开发时显示SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  # 格式化SQL日志
        use_sql_comments: true

  redis:
    host: localhost
    port: 6379
    password: ''         # 无密码留空字符串
    database: 0          # 默认DB
    timeout: 10000        # 连接超时(ms)

# 自定义JWT配置
app:
  jwt:
    secret: ZFXeAFTZZev/BdnRonEppEXwgQFHQA34NeL/SrUk2rQ= # 至少32位
    expiration-ms: 86400000  # 24小时